### ISSUE TITLE
how to make default as click shapes?

### ISSUE THREAD

**Issue by sprappcom** [wenlng/go-captcha-example#3]
1. how to make it show in click shapes as default?
2. how to make it all english?
3. how to skip the "click to show the captcha image?", just show without clicking.

**Comment by wenlng** [comment]
Hi, See if the following reference can help you.

1. Create a click of the graph type by using MakeWithShape() in click.newBuilder ().
https://github.com/wenlng/go-captcha-example/blob/b6134768a47dacbe32ff6e4d653e41ffd1ad4ced/internal/logic/captdata/click_shape.go#L20

2. Select a front-end library and configure it to display English, for React example, configure the "config" field in a React component instance.
https://github.com/wenlng/go-captcha-react/blob/v2/README.md#parameter-reference

3. You refer to the example of the front end, the button and the captcha can be freely controlled.
https://github.com/wenlng/go-captcha-example/tree/v2/web
