### ISSUE TITLE
CheckCacheOvertimeFile and ClearCaches in cache.go trigger deadlocks with each other

### ISSUE THREAD

**Issue by mugood** [wenlng/go-captcha-example#5]
The defer mux of checkCacheOvertimeFile Unlock() should be changed to mux Unlock()：
For example:
func checkCacheOvertimeFile() {
	mux.RLock()
	var keys = make([]string, 0)
	for key, data := range cachemaps {
		ex := time.Now().Unix() - data.createAt.Unix()
		if ex > (60 * 30) {
			keys = append(keys, key)
		}
	}
	mux.RUnlock()
	ClearCaches(keys)
}

**Comment by wenlng** [comment]
Yes, This issue has been fixed, Please use Redis cache for production environment.
